version: '3'
services:
  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/server
    command: flask run

  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    links:
      - server
    command: npm start